### ISSUE TITLE
Invalid token . in paimon-moe/__sapper__/build/server/server.js:80442

### ISSUE THREAD

**Issue by jackthenewbie** [MadeBaruna/paimon-moe#264]
```
/mnt/c/Users/caoth/Code/outsideCode/paimon-moe/__sapper__/build/server/server.js:80442
                      ${(character[set.id]?.[char])
                                           ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
timed out waiting for connection
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
johnc@Pi:/mnt/c/Users/caoth/Code/outsideCode/paimon-moe$`
```
What can i do now ? Ran with ``yarn export``

**Comment by jackthenewbie** [comment]
> are you trying to build the site? make sure to have nodejs 14+

ye my node -v was 10.x.x on wsl, accidentally ran on it, solve by run on ps instead. Thanks
